sudo: required
language: c++
compiler:
    - g++

before_install:
    - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
    - sudo apt-get -qq update
    - sudo apt-get install -y gcc-arm-embedded libusb-dev

script:
    - make clean test
    - ls -lah
